spring:
  application:
    name: send

server:
  port: 8082
#  servlet:
#    context-path: /send

zuul:
  routes:
    mark-service:
      path: /books/**
      serviceId: mark-service
#      stripPrefix: false

mark-service:
  ribbon:
    listOfServers: http://localhost:9001
    ContectTimeOut: 3000
    ReadTimeOut: 50000

ribbon:
  eureka:
    enabled: false


security:
  oauth2:
    client:
      clientId: yong
      clientSecret: passw0rd
      accessTokenUri: http://127.0.0.1:8081/api/oauth/token
      userAuthorizationUri: http://127.0.0.1:8081/api/oauth/authorize
    resource:
      userInfoUri: http://127.0.0.1:8081/api/user/me
      preferTokenInfo: false