server:
  port: 8081
  servlet:
    context-path: /api
#
spring:
  application:
      name: yong-security
  data:
    mongodb:
      uri: mongodb://localhost:27017/security
      database: security
security:
  headers:
    content-type: true

logging:
  level:
    com.yong: DEBUG
    org.springframework.security: INFO

yong:
  oauth:
    enable: true
    resource: yong
  debug:
    enable: true
