server:
  port: 8084

management:
  security:
    enabled: false

spring:
  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      auto-offset-reset: earliest
  application:
    name: yong-kafka-send
  cloud:
    stream:
      bindings:
        demoIn:
          destination: demo
          consumer:
            headerMode: raw
          group: testGroup
        demoOut:
          destination: demo
          producer:
            headerMode: raw