server:
  port: 8084

management:
  security:
    enabled: false

spring:
  application:
    name: yong-kafka-send
  kafka:
    consumer:
      auto-offset-reset: earliest
      group-id: testEmbeddedKafkaApplication
      key-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
  cloud:
    stream:
      bindings:
        demoIn:
          destination: demo
          consumer:
            headerMode: raw
          group: embeddedKafkaApplication
#          content-type: application/x-java-serialized-object;type=java.lang.String
#          content-type: application/json
        demoOut:
          destination: demo
          producer:
            headerMode: raw
#          content-type: application/x-java-serialized-object;type=java.lang.String
#          content-type: text/plain
#          content-type: application/json
#      kafka:
#        binder:
#          binders:
#            - 127.0.0.1
#          zk-nodes:
#            - 127.0.0.1
#          replicationFactor: 1
#          autoCreateTopics: true
#      default:
#        group: ${spring.application.name}
#        content-type: application/x-java-serialized-object;type=java.lang.String
