server:
  port: 8084

management:
  security:
    enabled: false

spring:
  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      auto-offset-reset: earliest
  application:
    name: yong-kafka-gateway
  cloud:
    stream:
      bindings:
        demoIn:
          destination: demo
          content-type: application/x-java-serialized-object;type=java.lang.String
#          consumer:
#            headerMode: raw
          group: testGroup
        demoOut:
          destination: demo
          content-type: application/x-java-serialized-object;type=java.lang.String
#          producer:
#            headerMode: raw